package com.flaringapp.elevator_core.modes.directioned

import com.flaringapp.elevator_core.elevator_behaviour.ElevatorBehaviour

interface DirectionedElevatorBehaviour : ElevatorBehaviour, DirectionedElevatorPanel